-- Tableau Prep flow: L02 - Planning Detailed
-- Flow LUID: e33f5f84-f21d-4bc4-9575-a8f5a7751419
-- Output data source: L03 - Planning Detailed DS
-- Created by Autom8 on 2026-10-08

{{ config(materialized='view') }}

with l01_planning_ds as (
    select * from {{ ref('l01_planning_ds') }}
),

l01_hubspot_deals_ds as (
    select * from {{ ref('l01_hubspot_deals_ds') }}
),

join_1 as (
    select
        l01_planning_ds.*,
        l01_hubspot_deals_ds.additional_information,
        l01_hubspot_deals_ds.bill_rate,
        l01_hubspot_deals_ds.category,
        l01_hubspot_deals_ds.close_date,
        l01_hubspot_deals_ds.currency,
        l01_hubspot_deals_ds.current_stage,
        l01_hubspot_deals_ds.customer_hk,
        l01_hubspot_deals_ds.deal_currency_code,
        l01_hubspot_deals_ds.deal_description,
        l01_hubspot_deals_ds.deal_detail_amount_eur,
        l01_hubspot_deals_ds.deal_detail_amount_gbp,
        l01_hubspot_deals_ds.deal_detail_amount,
        l01_hubspot_deals_ds.deal_detail_cost_eur,
        l01_hubspot_deals_ds.deal_detail_cost_gbp,
        l01_hubspot_deals_ds.deal_detail_cost,
        l01_hubspot_deals_ds.deal_detail_create_date,
        l01_hubspot_deals_ds.deal_detail_description,
        l01_hubspot_deals_ds.deal_detail_discount_eur,
        l01_hubspot_deals_ds.deal_detail_discount_gbp,
        l01_hubspot_deals_ds.deal_detail_discount_percentage,
        l01_hubspot_deals_ds.deal_detail_discount,
        l01_hubspot_deals_ds.deal_detail_hk_1,
        l01_hubspot_deals_ds.deal_detail_hk,
        l01_hubspot_deals_ds.deal_detail_id as deal_detail_id_1,
        l01_hubspot_deals_ds.deal_detail_margin_eur,
        l01_hubspot_deals_ds.deal_detail_margin_gbp,
        l01_hubspot_deals_ds.deal_detail_margin,
        l01_hubspot_deals_ds.deal_detail_price_eur,
        l01_hubspot_deals_ds.deal_detail_price_gbp,
        l01_hubspot_deals_ds.deal_detail_price,
        l01_hubspot_deals_ds.deal_details,
        l01_hubspot_deals_ds.deal_entity,
        l01_hubspot_deals_ds.deal_hk_1,
        l01_hubspot_deals_ds.deal_hk,
        l01_hubspot_deals_ds.deal_id as deal_id_2,
        l01_hubspot_deals_ds.deal_name_uppercase,
        l01_hubspot_deals_ds.deal_name as deal_name_1,
        l01_hubspot_deals_ds.deal_pipeline,
        l01_hubspot_deals_ds.deal_type as deal_type_1,
        l01_hubspot_deals_ds.domain,
        l01_hubspot_deals_ds.fivetran_order,
        l01_hubspot_deals_ds.hours,
        l01_hubspot_deals_ds.invoicing,
        l01_hubspot_deals_ds.last_activity_date,
        l01_hubspot_deals_ds.notes_for_invoicing,
        l01_hubspot_deals_ds.owner_hk,
        l01_hubspot_deals_ds.product_description,
        l01_hubspot_deals_ds.product,
        l01_hubspot_deals_ds.quantity,
        l01_hubspot_deals_ds.snowflake_order,
        l01_hubspot_deals_ds.sub_category,
        l01_hubspot_deals_ds.tableau_order,
        l01_hubspot_deals_ds.vendor
    from l01_planning_ds
    inner join l01_hubspot_deals_ds
        on l01_planning_ds.deal_detail_id = l01_hubspot_deals_ds.deal_detail_id
),

final as (
    select
        customer_name,
        deal_close_date,
        deal_detail_id,
        deal_id,
        deal_name,
        deal_owner_name,
        deal_type,
        employee_birthday_date,
        employee_country,
        employee_email_address_1,
        employee_email_address,
        employee_end_date,
        employee_first_name,
        employee_full_name,
        employee_hk,
        employee_id_1,
        employee_id,
        employee_last_name,
        employee_member_type,
        employee_name,
        employee_role_1,
        employee_role,
        employee_start_date_1,
        employee_start_date,
        employee_status_1,
        employee_status,
        employee_team_1,
        employee_team,
        engagement_code,
        engagement_date,
        engagement_hours,
        first_available_date,
        hubspot_url,
        is_public_holiday,
        planning_status,
        product_category,
        product_name,
        reports_to,
        request_date,
        request_details,
        shortcode,
        tabmove,
        tabmove_1,
        username_1,
        username,
        week_number,
        additional_information,
        bill_rate,
        category,
        close_date,
        currency,
        current_stage,
        customer_hk,
        deal_currency_code,
        deal_description,
        deal_detail_amount_eur,
        deal_detail_amount_gbp,
        deal_detail_amount,
        deal_detail_cost_eur,
        deal_detail_cost_gbp,
        deal_detail_cost,
        deal_detail_create_date,
        deal_detail_description,
        deal_detail_discount_eur,
        deal_detail_discount_gbp,
        deal_detail_discount_percentage,
        deal_detail_discount,
        deal_detail_hk_1,
        deal_detail_hk,
        deal_detail_id_1,
        deal_detail_margin_eur,
        deal_detail_margin_gbp,
        deal_detail_margin,
        deal_detail_price_eur,
        deal_detail_price_gbp,
        deal_detail_price,
        deal_details,
        deal_entity,
        deal_hk_1,
        deal_hk,
        deal_id_2,
        deal_name_uppercase,
        deal_name_1,
        deal_pipeline,
        deal_type_1,
        domain,
        fivetran_order,
        hours,
        invoicing,
        last_activity_date,
        notes_for_invoicing,
        owner_hk,
        product_description,
        product,
        quantity,
        snowflake_order,
        sub_category,
        tableau_order,
        vendor
    from join_1
)

select * from final